FROM lexandro/java8-base

MAINTAINER Robert Stern <lexandro2000@<you know that big search company>.com

ADD apache-maven-3.2.5-bin.tar.gz /

ENV M2_HOME=apache-maven-3.2.5
ENV PATH=$M2_HOME/bin:$PATH
